### ISSUE TITLE
Using with RxSwift 2.6.0

### ISSUE THREAD

**Issue by alex-kepar** [safx/ObservableArray-RxSwift#7]
Is there version that compatible with RxSwift 2.6.0 and Swift 2.3 ?
Podspec file of the last version has the dependency to RxSwift ~>2.3.1

**Comment by safx** [comment]
No.
I'll release the version compatible with RxSwift 3.0.0 + Swift 3.0, and I have no plan to create for RxSwift 2.6.0 + Swift 2.3.
