### ISSUE TITLE
Does not work with Swift3/RxSwift Dependencies

### ISSUE THREAD

**Issue by KileyCaravella** [safx/ObservableArray-RxSwift#9]
This still requires `RxSwift (~> 2.3.1)` (meaning all updates to v2 of RxSwift), but to work with Swift3 it must be updated to require `RxSwift (~> 3.0.0)` at the very least.

**Comment by KileyCaravella** [comment]
@safx you need to change the dependency in the podspec to `s.dependency "RxSwift", '~> 3.0'` in order for it to work properly with RxSwift 3.0 (which is the Swift3 version.

**Comment by KileyCaravella** [comment]
@safx it seems like you've pushed the swift3 changes but haven't updated the pod.

**Comment by safx** [comment]
Sorry, I forgot about it.
I just pushed now. Thanks!
